"""Password encoding compatible with the JavaScript login page."""

from __future__ import annotations

import base64
import json
from urllib.parse import quote

from Crypto.Cipher import PKCS1_v1_5
from Crypto.PublicKey import RSA


PUBLIC_KEY = """-----BEGIN PUBLIC KEY-----
MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQDACwPDxYycdCiNeblZa9LjvDzb
iZU1vc9gKRcG/pGjZ/DJkI4HmoUE2r/o6SfB5az3s+H5JDzmOMVQ63hD7LZQGR4k
3iYWnCg3UpQZkZEtFtXBXsQHjKVJqCiEtK+gtxz4WnriDjf+e/CxJ7OD03e7sy5N
Y/akVmYNtghKZzz6jwIDAQAB
-----END PUBLIC KEY-----"""


def split_like_browser(value: str, size: int = 30) -> list[str]:
    """Split like the loop in ``src/common.js``.

    The browser calls ``substring(maxIndex, i)`` at every 30th index. Because
    JavaScript's end index is exclusive, the first block is 29 UTF-16 code
    units and subsequent blocks contain 30. That off-by-one is wire-visible.
    """

    if size < 2:
        raise ValueError("size must be at least 2")
    raw = value.encode("utf-16-le", "surrogatepass")
    units = len(raw) // 2
    if not units:
        return []

    boundaries = [size - 1]
    while boundaries[-1] < units:
        boundaries.append(boundaries[-1] + size)

    chunks: list[str] = []
    start = 0
    for boundary in boundaries:
        end = min(boundary, units)
        if end > start:
            chunks.append(raw[start * 2 : end * 2].decode("utf-16-le", "surrogatepass"))
        start = end
        if start == units:
            break
    return chunks


def encrypt_password(password: str) -> str:
    """Return the URL-encoded value generated by ``getSecretParam``."""

    if not password or not password.strip():
        return ""

    cipher = PKCS1_v1_5.new(RSA.import_key(PUBLIC_KEY))
    ciphertexts = [
        base64.b64encode(cipher.encrypt(chunk.encode("utf-8"))).decode("ascii")
        for chunk in split_like_browser(password)
    ]
    serialized = json.dumps(ciphertexts, ensure_ascii=False, separators=(",", ":"))
    return quote(serialized, safe="-_.!~*'()")
